### ISSUE TITLE
Survey Functionality

### ISSUE THREAD

**Issue by ElisiaW** [GatorEducator/gatorgrouper#235] opened 2019-03-08 02:14 UTC
# Description of the Issue
Currently, the questions in survey section of the web application can only be determined by the programmers, not by users. This means that educators cannot configure the survey to match their needs.

## Add Detailed Comment with More Information

1. The survey.html file currently contains sections for five questions and placeholders where individuals can input a text response. Instead, it would be beneficial for the feedback from surveys to be uniform, such as using radio buttons instead. 
2. The issue is that the survey should be editable so that users will be able to configure the questions to what is needed for their specific class, as this may vary based on the type of class this program is being used for. 
3. Would an editable survey make more logical sense than using one that is predetermined by programmers?

**Comment by aubreypc** [comment] 2019-03-08 18:10
Hi @ElisiaW, thanks for opening this issue! I agree that some kind of survey functionality should be implemented before we ship. I'm a little uncertain about whether there's enough time to implement customizable surveys, mostly because it seems like it would require a more interactive JavaScript UI rather than static forms rendered by Django.

In the `feature/survey` branch I have started working on a more minimal kind of survey, where students have the opportunity to mark other students as preferred. This will act as a scalar multiple on the compatibility score of students (see #229 for more discussion of this).

There is still work which needs to be done on the views, models, and templates for this feature, so anyone who is interested in working on it is welcome to! Feel free to reach out to me so that we can coordinate.

**Comment by aubreypc** [comment] 2019-03-11 14:30
Closing issue -- duplicate of #242

**Closed by aubreypc** 2019-03-11 14:30 UTC
Labels: design, enhancement, help-wanted, need-feedback, question
